CLI: Fix List accounts (#205)
- Currently has error, might be issue with v2

```bash
Error: HTTP status client error (400 Bad Request) for url (https://mainnet.helius-rpc.com/?api-key=)

Caused by:
    HTTP status client error (400 Bad Request) for url (https://mainnet.helius-rpc.com/?api-key=)
```
- Fixes these methods

```bash
crankers/src/vault_handler.rs
140:            .get_program_accounts_with_config(
179:            .get_program_accounts_with_config(

cli/src/restaking_handler.rs
1015:            .get_program_accounts_with_config(
1052:            .get_program_accounts_with_config(

cli/src/vault_handler.rs
1202:            .get_program_accounts_with_config(
```